# Generated by Django 4.2 on 2023-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_notification',
            field=models.DateField(blank=True, null=True, verbose_name='date_notification'),
        ),
    ]
